### ISSUE TITLE
Token Not Match with 3D secure

### ISSUE THREAD

**Issue by berkneis** [iyzico/iyzipay-magento2#10]
Merhabalar,

Magento 2.4.* versiyonunda 3D odemesi sonrasinda Token Not Match hatasi donduruyor.

Tesekkurler.

**Comment by yunusyuksel** [comment]
Merhaba,

@berkneis Aynı hatayı ben de almaktayım. Acaba bir çözüm bulabildiniz mi ?

**Comment by sozgat** [comment]
Merhaba @yunusyuksel ,

https://dev.iyzipay.com/tr/acik-kaynak/magento adresinden modülümüzün yenilenmiş/güncel versiyonununu indirebilirsiniz. Herhangi bir sorun yaşamanız durumunda entegrasyon@iyzico.com'a mail atabilirsiniz.

Geri bildiriminiz için teşekkürler.

**Comment by yunusyuksel** [comment]
Merhaba,
https://dev.iyzipay.com/tr/acik-kaynak/magento adresinde Magento 2.2.3+
Modülü
<https://github.com/iyzico/iyzipay-magento2/releases/download/1.0.0/iyzico_magento_1.0.0v.zip>
isimli
link üzerinden modülü indirip kurulumunu yaptım. Token not match hatası ile
yine karşılaştım. Müşteriden ücret alınıyor fakat magento tarafında sipariş
başarılı olmuyor. Ayrıca bu hata alınınca kullanıcı otomatik olarak logout
oluyor.

Magento 2.2.3+ iyzico ile Öde
<https://github.com/iyzico/iyzipay-magento2/releases/download/pwi-1.0.0/PayWithIyzico.zip>
Bir
de böyle bir modül var. 2si arasındaki fark nedir acaba? Bu modülü kurmayı
denedim fakat credential girilecek yeri bulamadım.

Saygılarımla,

Yunus Yüksel

**Comment by sozgat** [comment]
Merhaba @yunusyuksel,

Geliştirici ekibi olarak bildiriminizi incelemeye alacağız. Bu sorun Chrome Samesite Cookie politikasından dolayı kaynaklanmaktadır. Şu kısımdaki çözüm yöntemlerini deneyebilirsiniz: [magento-cookie-sorunu](https://hidonet.medium.com/chrome-80-magento-cookie-sorunu-%C3%A7%C3%B6z%C3%BCm%C3%BC-d5b7d55b00e3)

2. olarak, iyzico ile Öde modülümüz, Magento 2.2.3+ iyzico Öde Formu modülü ile birlikte çalışmaktadır. Yani ilk kurmuş olduğunuz modül üzerindeki api-secret key bilgilerini kullanmaktadır.  iyzico ile Öde seçeneği tıklandığında müşterilerinize kredi kartı, banka kartı, Korumalı Havale/EFT ve iyzico bakiye gibi alternatif ödeme yöntemlerini tek bir ödeme çözümü üzerinden sunabilirsiniz. Müşterileriniz alışverişlerinde iyzico hesaplarına yükledikleri iyzico bakiyeleri sayesinde kartsız ve anında tamamlanan ödeme deneyiminin tadını çıkartır.

Değerli geri bildiriminiz için teşekkürler.
