### ISSUE TITLE
Ödeme sayfası checkbox sorunu

### ISSUE THREAD

**Issue by gntlby** [iyzico/iyzipay-magento2#12]
Merhaba,
Magento 2.4.2 kullanıyoruz. Ödeme aşamasına gelindiğinde, şartlar ve koşullar checkbox larını işaretlemeden müşteri sipariş verebiliyor. (Yani kart bilgilerini girip ödeme yapabiliyor.)
Bunun hala bir çözümü yok mu? Ya da bu problemi bir tek ben mi yaşıyorum. 
Bu konuda desteğinizi rica ediyoruz.

**Comment by sozgat** [comment]
Merhaba @gntlby,

Ben iyzico geliştirme ekibinden, Said. Detaylı inceleme ve bilgi almak için entegrasyon@iyzico.com adresi ile iletişime geçebilir misiniz?

İyi günler dilerim.
