### ISSUE TITLE
Payment method, also Overlayscript is active by default

### ISSUE THREAD

**Issue by robin-homberg** [iyzico/iyzipay-magento2#17]
The Payment method itself, but more important the overlayscript is active by default by the configuration in etc/config.xml.

Since there are Magento2 Installations with multiple websites, where Iyzipay payment method should only be shown on a single of the multiple websites, this shouldn't be the case for a payment module.
If you install the module, the overlayscript will be shown on all websites, until it is disabled again in configuration. This is bad for customer experience.

**Comment by feyzullahdemir** [comment]
After Magento Admin login, open Stores -> Configuration page and select Sales -> Payment Methods from the left panel. There is an overlay script option on the page that opens. You can change or remove the location of the overlay script from this option.
