### ISSUE TITLE
Error when Saving Payment Config

### ISSUE THREAD

**Issue by robin-homberg** [iyzico/iyzipay-magento2#18]
### Reproduction
When Saving Payment Configuration on Website Scope in Adminpanel i get the following error:
```
Something went wrong while saving this configuration: Notice: Undefined index: value in /var/www/html/vendor/iyzico/module-iyzipay/Observer/IyzipayConfigSaveBefore.php on line 72
```

### Code Issue
This already relates to the Observer where this bug persists.

The issue here are references on the config values fields such as: 
`$postData['groups']['iyzipay']['fields']['api_key']['value'];`
This does not work, because there is no `value` index in the array if you have 'Use Default' checkmark active for this config. Instead there is just an array index called `inherit`.

### Additional Information
Additionally it would be very good if all the logic to get the protectedShopId config, which is done in the mentioned Observer, would only be called if iyzipay payment method is actually active.

**Comment by nuovecode** [comment]
Same here
