### ISSUE TITLE
Configuration kaydetme hatası

### ISSUE THREAD

**Issue by gntlby** [iyzico/iyzipay-magento2#21]
Merhaba,

Adminde tüm ayarları yaptıktan sonra kaydet diyince aşağıdaki hatayı alıyorum.

Something went wrong while saving this configuration: Deprecated Functionality: end(): Calling end() on an object is deprecated in public_html/app/code/Iyzico/Iyzipay/Controller/IyzicoBase/IyzicoPkiStringBuilder.php on line 106

Magento 2.4.6 CE

**Comment by feyzullahdemir** [comment]
Merhaba @gntlby  , lütfen https://dev.iyzipay.com/tr/acik-kaynak/magento link üzerinden güncel sürümü indiriniz.Eğer sorunuz devam ediyor ise entegrasyon@iyzico.com üzerinden bizlerle iletişime geçebilirsiniz.
