### ISSUE TITLE
Bu ne biçim repo yönetimi

### ISSUE THREAD

**Issue by mucan54** [iyzico/iyzipay-magento2#22]
Koskoca iyzico, hangi branch güncel, hangi versiyonu kullanmalıyız, hiçbir bilgi yok. Ne iş yapıyorsunuz siz?

**Comment by tarikkamat** [comment]
Selamlar, 2.2.3+ branch'i günceldir. magento 2.2.3+ versiyonunu desteklemektedir.

**Comment by mucan54** [comment]
Bu dün güncellenmiş https://github.com/iyzico/iyzipay-magento2/tree/v2.1.4
bu ise geçen sene https://github.com/iyzico/iyzipay-magento2/tree/2.2.3%2B

2.1.4'ü güncellemeye devam ediyorsunuz ama en güncel versiyon nasıl oluyorda 2.2.3 oluyor.

Yeni doğrulama sistemine geçiş için 2.2.3'ü kullanamayız heralde en son geçen sene güncellediğiniz kod, yeni çıkan bir güncellemeyi desteklemiyordur.

https://docs.iyzico.com/on-hazirliklar/kimlik-dogrulama/hmacsha256-kimlik-dogrulama?utm_source=dengage&utm_medium=email&utm_campaign=fintech_verification_0811_2_email&dn_channel=email&dn_send_id=1121

Kendi modülümüzü mü yazmalıyız? Yoksa bir güncelleme yapılacak mı? Güncel dediğiniz branch 1 yıllık.

@tarikkamat

**Comment by tarikkamat** [comment]
Selamlar,

15 aralık'a kadar paylaştığımı kullanabilirsiniz. v2.1.4 henüz qa test aşamasında güncellendiğinde master branchine merge edilecektir. 

15 aralık'a kadar kullanabilirsiniz deme sebebim; auth v2 için uygun değil.

v2.1.4 sürümü ise; auth v2 sürümüne uygun çalışacaktır. Ek olarak; order-first yaklaşımından payment-first yaklaşımıyla geliştirmeye devam ediyoruz. Daha güvenli çalışmaya başlayacaktır.

**Comment by mucan54** [comment]
O zaman kendi modülümüzü yazacağız anlaşılan. 

![image](https://github.com/user-attachments/assets/349ced6a-8a52-4c65-ade1-1f7ea497e288)

**Comment by tarikkamat** [comment]
Ben iyzico'da entegrasyon mühendisi olarak çalışmaktayım. 30 Kasım olarak duyuru çıkıldığının farkındayım. İş önceliklerinden dolayı şu an yalnızca woocommerce altyapısı bu duyurudaki konu için eklenti güncellendi. Magento şu an qa testleri sürecinde süreç tamamlandıktan sonra bahsi geçen webhook, signature ve auth v2 özelliklerini destekliyor olacaktır.

30 kasım doğru fakat magento eklentimizi kullananlar için 15 aralığa kadar süreci uzattık. Dilerseniz eklentinin yeni versiyonu çıkana kadar bahsetmiş olduğum versiyonu kullanabilir ardından güncel versiyona update işlemi yapabilirsiniz veyahut tabi kide dökümanımız herkese açık olduğundan kendinizde magento için ödeme geçici eklentisi geliştirebilirsiniz.

**Comment by mucan54** [comment]
Cevabınız için teşekkür ederim. Ancak benim sorum şu, kendi modülümüzü yazmamız gerekiyor mu?

Yani çalışmakta olduğunuz versiyon 15 Aralıktan önce yayına çıkabilecek mi? Yani biz sizin çıkacağınız modülü beklersek herhangi bir gecikme yaşamadan geçiş sağlayabilir miyiz? Bu sorunun cevabına göre yeni modül yazıp yazmamamın gerekliliğine karar verebiliriz.
