### ISSUE TITLE
Magento 2.3 

### ISSUE THREAD

**Issue by ozanyeni** [iyzico/iyzipay-magento2#3]
We have installed the module in our system which has magento 2.3 properly. We're facing the payment. During the test, the bank withdraws money. But the process does not appear successful page and again we receive a return to the cargo information page.

**Comment by mehmetselim** [comment]
Hi @ozanyeni , I am from the iyzico developer team. Thank you for your feedback. 
For solution, our team of integration@iyzico.com has contacted you.
