### ISSUE TITLE
Invalid template file

### ISSUE THREAD

**Issue by gntlby** [iyzico/iyzipay-magento2#4]
Merhaba, yüklemeyi yaptım ama şu şekilde bir hata alıyoruz:
Invalid template file: 'order/totals.phtml' in module: 'Iyzico_Iyzipay' block's name: 'order_totals'
Teşekkürler.

**Comment by mehmetselim** [comment]
Merhaba @gntlby , iyzico geliştirici ekibindenim. Eklentimiz "Magento2 - 2.2+" versiyonları ile stabil olarak çalışmaktadır. Sorununuz ile ilgili  entegrasyon@iyzico.com adresi ile iletişime geçebilir misiniz ? 
Teşekkürler.
