### ISSUE TITLE
verison 2.2.7 magento2 order problem

### ISSUE THREAD

**Issue by secaliskan** [iyzico/iyzipay-magento2#5]
Hi, we are using iyzipay at our website for credit card payments. 
The problem is if the customer use iyzico as payment type magento order is not created in the system. Even in case the payment successfull magento does not create the order. And customer gets and error didt get the SUCCESS PAGE.
Please look the case and support us. We just upgrade from 1.9 and we are using iyzipay for 3 years.

**Comment by secaliskan** [comment]
Magento 2.2.7 order would not created in magento aftrer iyzico payment.
response did not return to site. and order would not placed...

**Comment by mehmetselim** [comment]
Hello @secaliskan, from the iyzico developer team

Our integration team has contacted you to help you. 
Thank you for your valuable feedback.
