### ISSUE TITLE
Sipariş maili gönderilmiyor.

### ISSUE THREAD

**Issue by cizgidekiadam** [iyzico/iyzipay-magento2#7]
Merhaba,

Magento 2.2.3 ve bu modülü kullanıyoruz.
Sipariş tamamlandığında onay maili gitmiyor. Manuel göndermek zorunda kalıyoruz.
Havale ile ya da diğer ödeme yöntemleri ile verilen siparişlerde sorun olmuyor. 

Kontrol ederseniz sevinirim.

**Comment by mehmetselim** [comment]
Merhabalar @rbostan 

Geri bildiriminizi ürün ekibimize ilettik değerli geri bildiriminiz için çok teşekkür ederiz.
