### ISSUE TITLE
Module Magento 2.3 Payment Problem

### ISSUE THREAD

**Issue by serhatcolak** [iyzico/iyzipay-magento2#8]
I have a problem with your module. I am using it in 2.2.9 without any problem. After upgrade to 2.3 when placing order with 3dsecure, I am re-directing to 3dsecure page as normal, but on returning from 3dsecure, I am re-directed to the home page with "Invalid Form Key. Please refresh the page." fault. Iyzıco get payment but magento not create order. I search the problem is because in Magento 2.3 core payment methods are using CsrfAwareActionInterface for each controller. Can you please to implement it. Thanks for your help.

**Comment by enginozsozgun** [comment]
Hi @serhatcolak , 
If you can forward your e-mail address to integration@iyzico.com, we will be happy to help.
